[package]
name = "fractalz"
version = "0.1.0"
authors = ["Kerollmops <renault.cle@gmail.com>"]

[dependencies]
num-complex = "0.1"
image = "0.18"
palette = "0.3"
rand = "0.4"
pathfinding = "0.6"

[profile.release]
debug = true
