[package]
name = "fractalz"
version = "0.1.0"
authors = ["Kerollmops <renault.cle@gmail.com>"]

[dependencies]
num-complex = "0.1"
image = "0.18"
png = "0.11"
palette = "0.3"
rand = "0.4"
rand_derive = "0.3"
pathfinding = "0.6"
structopt = "0.2"
chrono = "0.4"
egg-mode = "0.12"
futures = "0.1"
tokio-core = "0.1"

[features]
default = []
